/**
 * 
 */
package com.mobileum.roameranalytics.model;

/**
 * @author smruti
 *
 */

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Employee generated by hbm2java
 */

public class User implements java.io.Serializable {

	private Integer id;
	private String firstname;
	private String lastname;
	private String telephone;
	private String email;
	private Date created;
	private Date updated;
	private String password;
	private Integer createdBy;
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);

	public User() {
	}

	public User(Date created) {
		this.created = created;
	}

	public User(String firstname, String lastname, String telephone,
			String email, Date created, Date updated, String password,
			Integer createdBy) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.telephone = telephone;
		this.email = email;
		this.created = created;
		this.password = password;
		this.updated = updated;
		this.createdBy = createdBy;
	}

	public User(String firstname, String lastname, String telephone,
			String email, Date created, String password, Date updated,
			Integer createdBy, Set<UserRoles> userRoleses) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.telephone = telephone;
		this.email = email;
		this.created = created;
		this.password = password;
		this.userRoleses = userRoleses;
		this.updated = updated;
		this.createdBy = createdBy;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}


	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	
	public Set<UserRoles> getUserRoleses() {
		return userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

}

