    
	INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('NETWORK', 1, 1, 1);
    
    INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('ROAMING CATEGORY', 1, 2,2);
    
    INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('DOMESTIC ARPU', 1, 3,3);
    
    INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('PAYMENT TYPE', 1, 4,4);
    
    INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('DEVICE TYPE', 1, 5,5);
    
    INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('TRAFFIC PATTERN', 1, 6,6);
    
    INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('TRAVEL DURATION', 1, 7,7);
    
    INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('OTHER COUNTRIES TRAVELLED', 1, 8,8);
    
    INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('DOMESTIC LOCATION', 1, 9,9);
    
    INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('DOMESTIC DATA PROFILE', 1, 10,10);
    
    INSERT INTO attribute(attribute_name, module_id, display_order, attr_ind)
    VALUES ('ROAMING DATA PROFILE', 1, 11,11);
    
   
    
	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('same network group', 1,  1, 1);
	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('different network group', 2, 1,2);

    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SILENT', 1,  2, 1);
	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('VALUE', 2, 2,2);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('PREMIUM', 3, 2,3);
    
    
INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('LOW', 1,3,1);
INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('MEDIUM', 2,3,2);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('HIGH', 3,3,3);
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('PRE PAID', 1,4,1);
	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('POST PAID', 2,4,2);
    
	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('VALUE PHONE', 1,5,1);
	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('FEATURE PHONE', 2,5,2);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SMART PHONE', 3,5,3);
 	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('PREMIUM PHONE', 4,5,4);
	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('TABLET', 5,5,5);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('DONGLE', 6,5,6);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('M2M', 7,5,7);
    
    -- TRAFFIC PATTERN
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('MT ARBITRAGE', 1,6,1);
	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('TRAVEL SIM', 2,6,2);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('DUAL SIM', 3,6,3);
 	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('VOIP', 4,6,4);
	INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SEAMLESS CALL BACK',5,6, 5);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('AUDIO CONFERENCE', 6,6,6);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('INTERNATIONAL BUSINESS', 7,6, 7);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('M2M', 8,6, 8);
    
    --TRAVEL DURATION
    
        INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('WEEKDAY ONLY', 1,7,1);
INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('WEEKEND ONLY', 2,7,2);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('WEEKDAY PLUS WEEKEND', 3,7,3);
 INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('TWO WEEKS PLUS', 4,7,4);
    
    -- OTHER COUNTRIES TRAVELLED 
            INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('NEIGHBORING', 1,8,1);
INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('LEISURE', 2,8,2);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('LEISURE PREMIUM', 3,8,3);
 INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('BUSINESS', 4,8,4);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('LOW GDP', 5,8,5);
    
    -- DOMESTIC LOCATION
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('HOME', 1,9,1);
INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('WORK', 2,9, 2);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('LEISURE', 3,9, 3);
    
    
        -- DOMESTIC DATA PROFILE
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('ARTS & ENTERTAINMENT', 1, 10, 1);
INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('AUTO & VEHICLES', 2, 10, 2);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('BEAUTY & FITNESS', 3, 10, 3);
 INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('BUSINESS', 4, 10, 4);
INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('TECHNOLOGY & COMPUTING', 5, 10, 5);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('PERSONAL FINANCE', 6, 10, 6);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('FOOD & DRINK', 7, 10, 7);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('HOBBIES & INTEREST',8, 10, 8);
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('FAMILY & PARENTING', 9, 10, 9);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('HOME & GARDEN', 10, 10, 10);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('LAW & GOVERNMENT', 11, 10, 11);
    
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('NEWS', 12, 10, 12);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('ONLINE COMMUNITY', 13, 10, 13);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SOCIETY', 14, 10, 14);
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('PETS', 15, 10, 15);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SCIENCE', 16, 10, 16);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SPORTS', 17, 10, 17);
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SHOPPING', 18, 10, 18);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('STYLE & FASHION', 19, 10, 19);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('TRAVEL', 20, 10, 20);
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('JOBS & EDUCATION', 21, 10, 21);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('RELIGION & SPIRITUALITY', 22, 10, 22);
    
    -- roaming data profile
     INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('ARTS & ENTERTAINMENT', 1, 11, 1);
INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('AUTO & VEHICLES', 2, 11, 2);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('BEAUTY & FITNESS', 3, 11, 3);
 INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('BUSINESS', 4, 11, 4);
INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('TECHNOLOGY & COMPUTING', 5, 11, 5);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('PERSONAL FINANCE', 6, 11, 6);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('FOOD & DRINK', 7, 11, 7);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('HOBBIES & INTEREST',8, 11, 8);
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('FAMILY & PARENTING', 9, 11, 9);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('HOME & GARDEN', 10, 11, 10);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('LAW & GOVERNMENT', 11, 11, 11);
    
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('NEWS', 12, 11, 12);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('ONLINE COMMUNITY', 13, 11, 13);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SOCIETY', 14, 11, 14);
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('PETS', 15, 11, 15);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SCIENCE', 16, 11, 16);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SPORTS', 17, 11, 17);
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('SHOPPING', 18, 11, 18);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('STYLE & FASHION', 19, 11, 19);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('TRAVEL', 20, 11, 20);
    
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('JOBS & EDUCATION', 21, 11, 21);
    INSERT INTO attribute_category(categ_name, display_order, attr_ind, categ_ind)
    VALUES ('RELIGION & SPIRITUALITY', 22, 11, 22);
    
    
    
    -- Insert script for trip added by smruti on 22-08-2014
    
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (1, 'airtel-india', 'IN', 123, 1234, 456, 4567, 919716202389, 123456789012345678, 1406872099, 1409464099, '1234567891234567', '12345678', 1, '1200-top', 100, 200, 12, 20, 5, 5, 1234, 3241, 50, 30, 20, 100, 50, 50, 6, 3, 3, 10, 5, 5, 3, 2, 1, 3, 2, 1, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'NIGERIA', 'MTN', 'INDIA', 'AIRTEL', 'LUMIA 800', 'NOKIA');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (2, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'GHANA', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (3, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'ENGLAND', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (4, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'NEPAL', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (5, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'ENGLAND', 'MTS', 'CHINA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (6, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'USA', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (7, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'SPAIN', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (8, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'ENGLAND', 'MTS', 'INDIA', 'IDEA', 'I-6', 'FRANCE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (9, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'INDIA', 'MTS', 'CHINA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (10, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'INDIA', 'MTS', 'CHINA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (11, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'RUSSIA', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (12, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'BRAZIL', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (13, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'MEXICO', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (14, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'CANADA', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (15, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'DUBAI', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (16, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'AUSTRALIA', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (17, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'ENGLAND', 'MTS', 'CHINA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (18, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'USA', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (19, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'SPAIN', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (20, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'ENGLAND', 'MTS', 'INDIA', 'IDEA', 'I-6', 'FRANCE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (21, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'INDIA', 'MTS', 'CHINA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (22, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'INDIA', 'MTS', 'CHINA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (23, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'RUSSIA', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (24, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'BRAZIL', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (25, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'MEXICO', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');
INSERT INTO trip (id, opcoid, roamtype, homemcc, homemnc, visitedmcc, visitedmnc, imsi, msisdn, starttime, endtime, imei, tac, chargingplan, priceplan, mocallcount, mocallminutes, mtcallcount, mtcallminutes, mosmscount, mtsmscount, uplink, downlink, mocallcountlocal, mocallcounthome, mocallcountothers, mocallminuteslocal, mocallminuteshome, mocallminutesothers, mtcallcountlocal, mtcallcounthome, mtcallcountothers, mtcallminuteslocal, mtcallminuteshome, mtcallminutesothers, mosmscountlocal, mosmscounthome, mosmscountothers, mtsmscountlocal, mtsmscounthome, mtsmscountothers, mocallcountquadroam, mocallminutesquadroam, mtcallcountquadroam, mtcallminutesquadroam, mosmscountquadroam, mtsmscountquadroam, uplinkquadroam, downlinkquadroam, tonnagequadroam, overalltripcategory, mocallcountquaddomestic, mocallminutesquaddomestic, mtcallcountquaddomestic, mtcallminutesquaddomestic, mosmscountquaddomestic, mtsmscountquaddomestic, uplinkquaddomestic, downlinkquaddomestic, tonnagequaddomestic, overalldomesticcategory, msisdntimestamp, imeitimestamp, chargingplanapproximity, starttimestring, endtimestring, visitedcountryname, visitednetworkname, homecountryname, homenetworkname, devicename, devicemanufacturer) VALUES (26, '"airtel-india"', 'IN', 122, 1224, 456, 4567, 918130244466, 9876543210, 1406872000, 1409464099, '12345612345612345', '12345123', 1, '200-low', 50, 50, 100, 100, 10, 10, 122, 234, 30, 20, 10, 30, 20, 10, 30, 20, 10, 30, 20, 10, 5, 3, 2, 5, 3, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 2, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4, NULL, NULL, 1, NULL, NULL, 'CANADA', 'MTS', 'INDIA', 'IDEA', 'I-6', 'APPLE');

--- insert sql for userinfo and user_roles table
INSERT INTO userinfo(username, password, enabled)     VALUES ('smruti', 'pass', TRUE);
INSERT INTO user_roles(role_name, username) VALUES ( 'ROLE_ADMIN', 'smruti');
