/**
 * 
 */
package com.mobileum.roameranalytics.enums;


/**
 * @author sarvesh
 *
 */
public enum FilterColumn {

	NETWORK(1),
	NETWORK_SAME(1),
	NETWORK_DIFF(2),
	
	
	ROAMING_CATEGEGORY(2),
	ROAMING_CATEGEGORY_SILENT(1),
	ROAMING_CATEGEGORY_VALUE(2),
	ROAMING_CATEGEGORY_PREMIUM(3),
	
	PAYMENT_TYPE(4),
	PAYMENT_TYPE_PREPAID(1),
	PAYMENT_TYPE_POSTPAID(0),
	
	DOMESTIC_ARPU(3),
	DOMESTIC_ARPU_HIGH(6),
	DOMESTIC_ARPU_MED(5),
	DOMESTIC_ARPU_LOW(4),
	
	TRAVEL_DURATION(7),
	TRAVEL_DURATION_WEEKDAY(1),
	TRAVEL_DURATION_WEEKEND(2),
	TRAVEL_DURATION_WEEKDAY_WEEKEND(3),
	TRAVEL_DURATION_TWO_WEEKS_PLUS(4),
	
	DEVICE_TYPE(5),
	DEVICE_TYPE_VALUE_PHONE(1),
	DEVICE_TYPE_FEATURE_PHONE(2),
	DEVICE_TYPE_SMART_PHONE(3),
	DEVICE_TYPE_PREMIUM_PHONE(4),
	DEVICE_TYPE_TABLET(5),
	DEVICE_TYPE_DONGLE(6),
	DEVICE_TYPE_M2M(7);
	
	
	
	
	
	
	private int ind;
	
	/**
	 * 
	 */
	private FilterColumn(int ind) {
		this.ind = ind;
	}
	
	/**
	 * @return the ind
	 */
	public int getInd() {
		return ind;
	}
	
}
